# Generated by Django 2.1.7 on 2019-03-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20190306_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team1Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team2Score',
            field=models.IntegerField(default=0),
        ),
    ]
