# Generated by Django 2.1.7 on 2019-03-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20190308_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team1Score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='team2Score',
            field=models.IntegerField(null=True),
        ),
    ]
