# Generated by Django 2.1.7 on 2019-03-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_request'),
        ('tournament', '0006_auto_20190317_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrolment',
            new_name='Enrollment',
        ),
    ]
