# Generated by Django 2.1.7 on 2019-04-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20190408_1621'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set(),
        ),
    ]
