# Generated by Django 2.1.7 on 2019-04-08 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0003_auto_20190407_1703'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('user', 'team')},
        ),
    ]
